/**
 * Generated by `supabase gen types typescript` against project
 * mwxokedrwjlyrqcwvdur. Do not hand-edit — regenerate after any schema
 * migration instead.
 *
 * IMPORTANT — trigger-maintained columns: do not set these from client code.
 * The database computes/guards them and silently discards client-supplied
 * values for anon/authenticated roles (see the `*_guard_client_columns`
 * triggers):
 *   - projects: upvote_count, comment_count, bookmark_count, view_count,
 *     hot_score, search_tsv
 *   - profiles: follower_count, following_count, project_count,
 *     total_upvotes_received
 *
 * IMPORTANT — visibility: `projects` RLS allows SELECT when
 * `visibility IN ('public','unlisted')` OR you're the author. This means
 * `unlisted` projects (and their images/tags/collaborators/comments, and
 * voting/bookmarking on them) are readable by anyone with the ID/slug —
 * RLS does NOT hide them from a direct query. Every feed/search/tag/
 * leaderboard query MUST explicitly add `.eq('visibility', 'public')` —
 * that app-layer filter is the only thing keeping unlisted projects out of
 * public listings. `projects_hot_feed_idx` / `projects_new_feed_idx` are
 * partial indexes on `visibility = 'public'`, so a correctly-filtered feed
 * query hits the index and a query missing the filter loses it — a feed
 * that starts seq-scanning is a cheap smoke signal someone dropped it.
 */
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      comment_votes: {
        Row: {
          comment_id: string
          created_at: string
          profile_id: string
          value: number
        }
        Insert: {
          comment_id: string
          created_at?: string
          profile_id: string
          value?: number
        }
        Update: {
          comment_id?: string
          created_at?: string
          profile_id?: string
          value?: number
        }
        Relationships: [
          {
            foreignKeyName: "comment_votes_comment_id_fkey"
            columns: ["comment_id"]
            isOneToOne: false
            referencedRelation: "comments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "comment_votes_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      bookmarks: {
        Row: {
          created_at: string
          profile_id: string
          project_id: string
        }
        Insert: {
          created_at?: string
          profile_id: string
          project_id: string
        }
        Update: {
          created_at?: string
          profile_id?: string
          project_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "bookmarks_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bookmarks_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      comments: {
        Row: {
          author_id: string
          body: string
          created_at: string
          deleted_at: string | null
          depth: number
          id: string
          parent_id: string | null
          project_id: string
          upvote_count: number
        }
        Insert: {
          author_id: string
          body: string
          created_at?: string
          deleted_at?: string | null
          depth?: number
          id?: string
          parent_id?: string | null
          project_id: string
          upvote_count?: number
        }
        Update: {
          author_id?: string
          body?: string
          created_at?: string
          deleted_at?: string | null
          depth?: number
          id?: string
          parent_id?: string | null
          project_id?: string
          upvote_count?: number
        }
        Relationships: [
          {
            foreignKeyName: "comments_author_id_fkey"
            columns: ["author_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "comments_parent_id_fkey"
            columns: ["parent_id"]
            isOneToOne: false
            referencedRelation: "comments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "comments_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      follows: {
        Row: {
          created_at: string
          follower_id: string
          following_id: string
        }
        Insert: {
          created_at?: string
          follower_id: string
          following_id: string
        }
        Update: {
          created_at?: string
          follower_id?: string
          following_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "follows_follower_id_fkey"
            columns: ["follower_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "follows_following_id_fkey"
            columns: ["following_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      leaderboard_previous: {
        Row: {
          captured_at: string
          entity_id: string
          kind: string
          rank: number
          win: string
        }
        Insert: {
          captured_at?: string
          entity_id: string
          kind: string
          rank: number
          win: string
        }
        Update: {
          captured_at?: string
          entity_id?: string
          kind?: string
          rank?: number
          win?: string
        }
        Relationships: []
      }
      media_cleanup_runs: {
        Row: {
          deleted_count: number
          deleted_paths: string[]
          error: string | null
          id: number
          ran_at: string
        }
        Insert: {
          deleted_count?: number
          deleted_paths?: string[]
          error?: string | null
          id?: never
          ran_at?: string
        }
        Update: {
          deleted_count?: number
          deleted_paths?: string[]
          error?: string | null
          id?: never
          ran_at?: string
        }
        Relationships: []
      }
      notifications: {
        Row: {
          actor_id: string | null
          comment_id: string | null
          created_at: string
          id: string
          project_id: string | null
          read_at: string | null
          recipient_id: string
          type: string
        }
        Insert: {
          actor_id?: string | null
          comment_id?: string | null
          created_at?: string
          id?: string
          project_id?: string | null
          read_at?: string | null
          recipient_id: string
          type: string
        }
        Update: {
          actor_id?: string | null
          comment_id?: string | null
          created_at?: string
          id?: string
          project_id?: string | null
          read_at?: string | null
          recipient_id?: string
          type?: string
        }
        Relationships: [
          {
            foreignKeyName: "notifications_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notifications_comment_id_fkey"
            columns: ["comment_id"]
            isOneToOne: false
            referencedRelation: "comments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notifications_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notifications_recipient_id_fkey"
            columns: ["recipient_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          avatar_url: string | null
          bio: string | null
          college: string | null
          created_at: string
          display_name: string | null
          follower_count: number
          following_count: number
          github_username: string | null
          grad_year: number | null
          headline: string | null
          id: string
          is_student: boolean
          links: Json
          location: string | null
          open_to_collab: boolean
          project_count: number
          roles: string[]
          timezone: string | null
          total_upvotes_received: number
          updated_at: string
          username: string | null
          weekly_hours_available: number | null
        }
        Insert: {
          avatar_url?: string | null
          bio?: string | null
          college?: string | null
          created_at?: string
          display_name?: string | null
          follower_count?: number
          following_count?: number
          github_username?: string | null
          grad_year?: number | null
          headline?: string | null
          id: string
          is_student?: boolean
          links?: Json
          location?: string | null
          open_to_collab?: boolean
          project_count?: number
          roles?: string[]
          timezone?: string | null
          total_upvotes_received?: number
          updated_at?: string
          username?: string | null
          weekly_hours_available?: number | null
        }
        Update: {
          avatar_url?: string | null
          bio?: string | null
          college?: string | null
          created_at?: string
          display_name?: string | null
          follower_count?: number
          following_count?: number
          github_username?: string | null
          grad_year?: number | null
          headline?: string | null
          id?: string
          is_student?: boolean
          links?: Json
          location?: string | null
          open_to_collab?: boolean
          project_count?: number
          roles?: string[]
          timezone?: string | null
          total_upvotes_received?: number
          updated_at?: string
          username?: string | null
          weekly_hours_available?: number | null
        }
        Relationships: []
      }
      project_collaborators: {
        Row: {
          created_at: string
          id: string
          invited_name: string | null
          position: number
          profile_id: string | null
          project_id: string
          role_label: string | null
          status: string
        }
        Insert: {
          created_at?: string
          id?: string
          invited_name?: string | null
          position?: number
          profile_id?: string | null
          project_id: string
          role_label?: string | null
          status?: string
        }
        Update: {
          created_at?: string
          id?: string
          invited_name?: string | null
          position?: number
          profile_id?: string | null
          project_id?: string
          role_label?: string | null
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "project_collaborators_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "project_collaborators_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      project_images: {
        Row: {
          alt: string | null
          caption: string | null
          created_at: string
          height: number | null
          id: string
          position: number
          project_id: string
          storage_path: string
          width: number | null
        }
        Insert: {
          alt?: string | null
          caption?: string | null
          created_at?: string
          height?: number | null
          id?: string
          position?: number
          project_id: string
          storage_path: string
          width?: number | null
        }
        Update: {
          alt?: string | null
          caption?: string | null
          created_at?: string
          height?: number | null
          id?: string
          position?: number
          project_id?: string
          storage_path?: string
          width?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "project_images_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      project_tags: {
        Row: {
          project_id: string
          tag_id: string
        }
        Insert: {
          project_id: string
          tag_id: string
        }
        Update: {
          project_id?: string
          tag_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "project_tags_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "project_tags_tag_id_fkey"
            columns: ["tag_id"]
            isOneToOne: false
            referencedRelation: "tags"
            referencedColumns: ["id"]
          },
        ]
      }
      project_views: {
        Row: {
          created_at: string
          id: string
          project_id: string
          viewed_on: string
          viewer_key: string
        }
        Insert: {
          created_at?: string
          id?: string
          project_id: string
          viewed_on?: string
          viewer_key: string
        }
        Update: {
          created_at?: string
          id?: string
          project_id?: string
          viewed_on?: string
          viewer_key?: string
        }
        Relationships: [
          {
            foreignKeyName: "project_views_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      projects: {
        Row: {
          author_id: string
          bookmark_count: number
          comment_count: number
          cover_image_path: string | null
          created_at: string
          description: string | null
          hot_score: number
          id: string
          live_url: string | null
          published_at: string | null
          repo_url: string | null
          search_tsv: unknown
          slug: string
          status: string
          tagline: string | null
          title: string
          updated_at: string
          upvote_count: number
          view_count: number
          visibility: string
        }
        Insert: {
          author_id: string
          bookmark_count?: number
          comment_count?: number
          cover_image_path?: string | null
          created_at?: string
          description?: string | null
          hot_score?: number
          id?: string
          live_url?: string | null
          published_at?: string | null
          repo_url?: string | null
          search_tsv?: unknown
          slug: string
          status?: string
          tagline?: string | null
          title: string
          updated_at?: string
          upvote_count?: number
          view_count?: number
          visibility?: string
        }
        Update: {
          author_id?: string
          bookmark_count?: number
          comment_count?: number
          cover_image_path?: string | null
          created_at?: string
          description?: string | null
          hot_score?: number
          id?: string
          live_url?: string | null
          published_at?: string | null
          repo_url?: string | null
          search_tsv?: unknown
          slug?: string
          status?: string
          tagline?: string | null
          title?: string
          updated_at?: string
          upvote_count?: number
          view_count?: number
          visibility?: string
        }
        Relationships: [
          {
            foreignKeyName: "projects_author_id_fkey"
            columns: ["author_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      reports: {
        Row: {
          comment_id: string | null
          created_at: string
          id: string
          project_id: string | null
          reason: string
          reporter_id: string
          status: string
        }
        Insert: {
          comment_id?: string | null
          created_at?: string
          id?: string
          project_id?: string | null
          reason: string
          reporter_id: string
          status?: string
        }
        Update: {
          comment_id?: string | null
          created_at?: string
          id?: string
          project_id?: string | null
          reason?: string
          reporter_id?: string
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "reports_comment_id_fkey"
            columns: ["comment_id"]
            isOneToOne: false
            referencedRelation: "comments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reports_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reports_reporter_id_fkey"
            columns: ["reporter_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      tags: {
        Row: {
          created_at: string
          id: string
          kind: string
          name: string
          slug: string
          usage_count: number
        }
        Insert: {
          created_at?: string
          id?: string
          kind: string
          name: string
          slug: string
          usage_count?: number
        }
        Update: {
          created_at?: string
          id?: string
          kind?: string
          name?: string
          slug?: string
          usage_count?: number
        }
        Relationships: []
      }
      votes: {
        Row: {
          created_at: string
          profile_id: string
          project_id: string
          value: number
        }
        Insert: {
          created_at?: string
          profile_id: string
          project_id: string
          value?: number
        }
        Update: {
          created_at?: string
          profile_id?: string
          project_id?: string
          value?: number
        }
        Relationships: [
          {
            foreignKeyName: "votes_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "votes_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      leaderboard_daily: {
        Row: {
          computed_at: string | null
          entity_id: string | null
          kind: string | null
          projects_in_window: number | null
          rank: number | null
          votes: number | null
          win: string | null
        }
        Relationships: []
      }
    }
    Functions: {
      compute_hot_score: {
        Args: { score: number; ts: string }
        Returns: number
      }
      feed_page: {
        Args: {
          p_cur_id?: string
          p_cur_num?: number
          p_cur_ts?: string
          p_limit?: number
          p_tab: string
          p_tag?: string
          p_viewer?: string
          p_window?: string
        }
        Returns: {
          author: Json
          comment_count: number
          cover_image_path: string
          hot_score: number
          id: string
          published_at: string
          slug: string
          status: string
          tagline: string
          tags: Json
          title: string
          upvote_count: number
          view_count: number
        }[]
      }
      leaderboard_builders: {
        Args: { p_limit?: number; p_window?: string }
        Returns: {
          avatar_url: string
          computed_at: string
          delta: number
          display_name: string
          headline: string
          id: string
          projects_in_window: number
          rank: number
          username: string
          votes: number
        }[]
      }
      leaderboard_projects: {
        Args: { p_limit?: number; p_window?: string }
        Returns: {
          author_display_name: string
          author_username: string
          computed_at: string
          cover_image_path: string
          delta: number
          id: string
          rank: number
          slug: string
          tags: Json
          title: string
          votes: number
        }[]
      }
      like_escape: { Args: { p_term: string }; Returns: string }
      orphaned_project_media: {
        Args: { p_limit?: number }
        Returns: {
          object_created_at: string
          object_name: string
        }[]
      }
      record_project_view: {
        Args: { p_project_id: string; p_viewer_key: string }
        Returns: undefined
      }
      refresh_leaderboard: { Args: never; Returns: undefined }
      related_tags: {
        Args: { p_limit?: number; p_slug: string }
        Returns: {
          name: string
          shared: number
          slug: string
          usage_count: number
        }[]
      }
      search_people: {
        Args: { p_limit?: number; p_q: string }
        Returns: {
          avatar_url: string
          display_name: string
          follower_count: number
          headline: string
          id: string
          total: number
          username: string
        }[]
      }
      search_projects: {
        Args: {
          p_limit?: number
          p_q: string
          p_status?: string[]
          p_tags?: string[]
        }
        Returns: {
          author: Json
          comment_count: number
          cover_image_path: string
          id: string
          published_at: string
          slug: string
          status: string
          tagline: string
          tags: Json
          title: string
          total: number
          upvote_count: number
          view_count: number
        }[]
      }
      search_tags: {
        Args: { p_limit?: number; p_q: string }
        Returns: {
          name: string
          slug: string
          total: number
          usage_count: number
        }[]
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
