export type ProjectIdea = {
  title: string;
  tagline: string;
  description: string;
  tags: string[];
  category?: string;
};

// Curated so seeded titles/descriptions read like real projects instead of
// lorem-ipsum noise — that matters here because the whole point of seeding
// is to eyeball whether the feed and ranking actually feel right.
export const PROJECT_IDEAS: ProjectIdea[] = [
  { title: "Kerbside", tagline: "Find street parking before you leave — crowd-reported spots, live on a map.", description: "Kerbside started as a class project after circling the block for 20 minutes three nights in a row. It maps crowd-reported open spots and decays them over time, so what you see is what's probably still there.", tags: ["react", "typescript", "postgresql"], category: "class-project" },
  { title: "Pantry", tagline: "Scan your groceries, get recipes for what's about to expire.", description: "Pantry watches expiry dates on what you've scanned and nudges you toward recipes that use the stuff about to go bad, instead of letting it rot in the back of the fridge.", tags: ["react-native", "expo", "supabase"] },
  { title: "Standup Bot", tagline: "Async daily standups for small teams, posted straight to Slack.", description: "A tiny bot that DMs your team a standup prompt every morning and threads the replies into one digest. Built because our team kept forgetting to post updates.", tags: ["node.js", "typescript", "docker"] },
  { title: "Gradient", tagline: "A color palette generator that actually understands accessibility contrast.", description: "Most palette tools optimize for looking nice in isolation. Gradient checks every pair against WCAG contrast ratios live as you drag, so you don't find out it's unreadable after shipping.", tags: ["react", "figma", "tailwind-css"], category: "side-project" },
  { title: "Flock", tagline: "Split-the-bill for group trips, without the spreadsheet.", description: "Built this after a ski trip ended in a very confusing group Venmo chain. Flock tracks who paid for what and settles the whole group in the minimum number of transfers.", tags: ["next.js", "typescript", "postgresql"] },
  { title: "Rehearse", tagline: "Practice technical interviews with an AI that actually asks follow-ups.", description: "Rehearse runs a live coding interview loop — it asks a question, watches you think out loud, and pushes back on your first answer the way a real interviewer would.", tags: ["python", "react", "machine-learning"] },
  { title: "Dorm Swap", tagline: "A campus-only marketplace for textbooks, furniture, and dorm stuff.", description: "Every semester ends with a dumpster full of perfectly good furniture. Dorm Swap is a marketplace scoped to one campus, verified with a .edu email, for exactly that stuff.", tags: ["next.js", "supabase", "tailwind-css"], category: "hackathon" },
  { title: "Loopcast", tagline: "Turn a GitHub repo's commit history into a weekly audio recap.", description: "Loopcast summarizes a week of commits and PRs into a 3-minute narrated recap, for teams who'd rather listen on a commute than read a changelog.", tags: ["node.js", "python", "aws"] },
  { title: "Shelfie", tagline: "Track what you've read, want to read, and lend to friends.", description: "A minimal reading tracker that also tracks who you lent physical books to, because that's the part every other reading app forgets exists.", tags: ["swift", "postgresql"] },
  { title: "Warmup", tagline: "A 5-minute daily coding kata generator scoped to your weakest topics.", description: "Warmup looks at what you've gotten wrong before and generates a short daily kata targeting exactly that, instead of a random LeetCode pick.", tags: ["typescript", "react", "node.js"], category: "side-project" },
  { title: "Nightshift", tagline: "A dashboard for tracking on-call rotations across small eng teams.", description: "PagerDuty felt like overkill for a 6-person team. Nightshift is a much smaller on-call calendar with Slack handoff reminders built in.", tags: ["react", "supabase", "tailwind-css"] },
  { title: "Fieldnote", tagline: "Voice-to-structured-notes for lab work, no typing with gloves on.", description: "Built with a bio lab friend who was tired of stripping off gloves to type notes. Fieldnote transcribes voice memos into structured, timestamped lab entries.", tags: ["python", "machine-learning", "react-native"] },
  { title: "Campfire", tagline: "A cozy, text-only chat app for small friend groups.", description: "Campfire deliberately has no read receipts, no typing indicators, and no algorithm — just a slow, warm group chat for people who want less anxiety from messaging.", tags: ["expo", "react-native", "supabase"], category: "side-project" },
  { title: "Blueprint", tagline: "Turn a Figma file into a working React component library.", description: "Blueprint reads Figma's component structure and generates a typed React component scaffold with matching props, so design and code drift apart less.", tags: ["typescript", "figma", "react"] },
  { title: "Tideline", tagline: "Surf condition forecasts blended from three different marine APIs.", description: "No single marine forecast API was reliable enough on its own, so Tideline blends three sources and shows the disagreement between them instead of hiding it.", tags: ["python", "react", "postgresql"] },
  { title: "Runbook", tagline: "Turn a postmortem doc into an actual runbook checklist.", description: "After enough 3am incidents where the postmortem's action items just sat in a doc forever, Runbook converts them into trackable checklist items with owners.", tags: ["go", "react", "docker"] },
  { title: "Sprout", tagline: "A plant care tracker that reads your local weather to adjust watering.", description: "Sprout pulls local humidity and rainfall so your watering schedule adjusts automatically instead of running on a fixed weekly timer that ignores an actual rainstorm.", tags: ["react-native", "expo", "postgresql"], category: "hackathon" },
  { title: "Office Hours", tagline: "A queue system for TA office hours that shows real wait times.", description: "Built after waiting 40 minutes in a physical line for office hours. Students join a virtual queue and see an honest estimated wait instead of guessing.", tags: ["next.js", "supabase", "typescript"], category: "class-project" },
  { title: "Patchwork", tagline: "Diff two API responses and get a human-readable summary of what changed.", description: "Patchwork is a small CLI + web tool for pasting two JSON blobs and getting back a plain-English summary of what changed, aimed at API migration reviews.", tags: ["rust", "typescript"] },
  { title: "Groundwork", tagline: "A project-based interview prep tracker for new grads.", description: "Groundwork tracks applications, interview stages, and prep notes per company in one board, built during a job search that had gotten too messy for spreadsheets.", tags: ["react", "node.js", "postgresql"], category: "side-project" },
  { title: "Afterhours", tagline: "Find open study rooms on campus in real time.", description: "Afterhours pings campus room-booking systems and shows which study rooms are actually free right now, instead of the stale weekly schedule posted on the door.", tags: ["react-native", "expo", "supabase"] },
  { title: "Signal Boost", tagline: "A newsletter digest generator for open-source project maintainers.", description: "Signal Boost watches a repo's issues, PRs, and discussions and drafts a monthly community update, so maintainers spend less time writing recap emails.", tags: ["node.js", "typescript", "aws"] },
  { title: "Undertow", tagline: "A minimalist habit tracker with no streak-shaming.", description: "Undertow deliberately doesn't punish broken streaks — it shows a rolling trend line instead, because streak anxiety was the actual reason every other habit app got deleted.", tags: ["swift", "postgresql"], category: "side-project" },
  { title: "Common Room", tagline: "A shared watchlist app for roommates deciding what to watch.", description: "Common Room merges everyone's streaming watchlists and surfaces the overlap first, ending the nightly 20-minute negotiation over what to put on.", tags: ["react", "next.js", "tailwind-css"] },
  { title: "Waypoint", tagline: "Turn a rough road-trip itinerary into an optimized route with stops.", description: "Waypoint takes a loose list of places you want to hit on a road trip and reorders them into a sane route, with gas and food stops factored in.", tags: ["python", "react", "postgresql"] },
  { title: "Threadline", tagline: "A lightweight issue tracker that lives entirely inside GitHub Discussions.", description: "Threadline is a bot + small UI that turns GitHub Discussions into a kanban-style issue tracker for teams who don't want a second tool to keep in sync.", tags: ["typescript", "node.js", "react"] },
  { title: "Basecamp Notes", tagline: "Offline-first field notes app for hikers, syncs when back in range.", description: "Built after losing a full day of trail notes to no signal. Everything's stored locally first and syncs opportunistically whenever a connection shows up.", tags: ["expo", "react-native", "supabase"], category: "side-project" },
  { title: "Ledgerline", tagline: "A tiny personal finance tracker that categorizes spending with an LLM.", description: "Ledgerline imports a bank CSV export and uses an LLM to auto-categorize transactions, then lets you correct and retrain the categorization from those corrections.", tags: ["python", "machine-learning", "react"] },
  { title: "Greenroom", tagline: "A show-day checklist and cue-sheet app for small theater productions.", description: "Built with a college theater group tired of paper cue sheets. Greenroom tracks lighting/sound cues and lets stage managers check them off live during a show.", tags: ["react", "supabase", "tailwind-css"], category: "class-project" },
  { title: "Hollow Knight of Bugs", tagline: "A gamified bug bounty board for open-source triage days.", description: "Turns a maintainer's backlog triage day into a small game — contributors claim issues, earn points for good repro steps, and a leaderboard tracks the day's progress.", tags: ["next.js", "typescript", "postgresql"], category: "hackathon" },
];
